config/routes.rb
Rails.application.routes.draw do
  root 'decks#index'
  resources :decks do
    resources :cards
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :deck

  validates :front, presence: true
  validates :back, presence: true
end

app/models/deck.rb
class Deck < ApplicationRecord
  has_many :cards, dependent: :destroy

  validates :title, presence: true
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def index
    @deck = Deck.find(params[:deck_id])
    @cards = @deck.cards
  end

  def show
    @card = Card.find(params[:id])
  end

  def new
    @deck = Deck.find(params[:deck_id])
    @card = Card.new
  end

  def create
    @deck = Deck.find(params[:deck_id])
    @card = Card.new(card_params)
    @card.deck = @deck

    if @card.save
      redirect_to deck_path(@deck)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @deck = Deck.find(params[:deck_id])
    @card = Card.find(params[:id])
  end

  def update
    @deck = Deck.find(params[:deck_id])
    @card = Card.find(params[:id])
    if @card.update(card_params)
      redirect_to deck_card_path(@deck, @card)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @card = Card.find(params[:id])
    @deck = @card.deck
    @card.destroy
    redirect_to deck_cards_path(@deck)
  end

  private

  def card_params
    params.require(:card).permit(:front, :back)
  end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :set_deck, only: [:show, :edit, :update, :destroy]

  def index
    @decks = Deck.all
  end

  def show
  end

  def new
    @deck = Deck.new
  end

  def create
    @deck = Deck.new(deck_params)

    if @deck.save
      redirect_to deck_path(@deck)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @deck.update(deck_params)
      redirect_to deck_path(@deck)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @deck.destroy
    redirect_to decks_path, status: :see_other
  end

  private

  def deck_params
    params.require(:deck).permit(:title, :description)
  end

  def set_deck
    @deck = Deck.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/views/cards/_form.html.erb
<%= simple_form_for [deck, card] do |f| %>
  <%= f.input :front %>
  <%= f.input :back %>
  <%= f.submit %>
<% end %>

app/views/cards/edit.html.erb
<div class="container">
  <%= link_to 'Home', root_path %>
  <h1>Edit Card</h1>
  <%= render 'form', card: @card, deck: @deck %>
</div>

app/views/cards/index.html.erb
<div class="container">
  <%= link_to 'Home', root_path %>
  <h1>Cards</h1>
  <% @cards.each do |card| %>
    <p><%= link_to card.front, deck_card_path(@deck, card) %></p>
  <% end %>
</div>

app/views/cards/new.html.erb
<div class="container">
  <%= link_to 'Home', root_path %>
  <h1>New Card</h1>
  <%= render 'form', deck: @deck, card: @card %>
</div>

app/views/cards/show.html.erb
<div class="container">
  <%= link_to 'Home', root_path %>
  <%= link_to 'Edit Card', edit_deck_card_path(@card.deck, @card) %>
  <h2>Front: <%= @card.front %></h2>
  <h2>Back: <%= @card.back %></h2>
  <%= link_to 'Destroy Card', deck_card_path(@card.deck, @card), data: {
    turbo_method: :delete,
    turbo_confirm: 'Are you sure?'
  } %>
</div>

app/views/decks/_form.html.erb
<%= simple_form_for deck do |f| %>
  <%= f.input :title %>
  <%= f.input :description %>
  <%= f.submit %>
<% end %>

app/views/decks/edit.html.erb
<div class="container">
  <%= link_to 'Home', root_path %>
  <h1>Edit Deck</h1>
  <%= render 'form', deck: @deck %>
</div>

app/views/decks/index.html.erb
<div class="container">
  <h1>Decks</h1>
  <% @decks.each do |deck| %>
    <div>
      <h2><%= link_to deck.title, deck_path(deck) %></h2>
      <p><%= deck.description %></p>
    </div>
  <% end %>
  <%= link_to 'New Deck', new_deck_path %>
</div>

app/views/decks/new.html.erb
<div class="container">
  <%= link_to 'Home', root_path %>
  <h1>New Deck</h1>
  <%= render 'form', deck: @deck %>
</div>

app/views/decks/show.html.erb
<div class="container">
  <%= link_to 'Home', root_path %>
  <h1><%= @deck.title %></h1>
  <div>
    <%= link_to 'Cards', deck_cards_path(@deck) %>
    <%= link_to 'New Card', new_deck_card_path(@deck) %>
  </div>
  <p><%= @deck.description %></p>
  <div>
    <%= link_to 'Edit Deck', edit_deck_path(@deck) %>
    <%= link_to 'Destroy Deck', deck_path(@deck), data: {
      turbo_method: :delete,
      turbo_confirm: 'Are you sure?'
    } %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flashcards</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>